# Generated by Django 3.2.6 on 2023-01-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230131_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ppoi',
        ),
    ]
